### PR TITLE
Code refactoring and action updates for correct functionality

### PR DESCRIPTION
**Pull request by iamdharmesh**
### Description of the Change
This PR initiates some initial code refactoring and updates the code to ensure that the action functions correctly.

@desrosj Please let me if you need any further information related to this PR.

cc: @jeffpaul

### How to test the Change
1. Set up this action on the specific repository (`iamdharmesh/wordpress-props@main` to test this PR). An example workflow file can be found in the README.md file.
1. Create an issue on the repository.
1. Raise a sample PR that fixes that issue.
1. Verify that the action adds a comment on the PR with a list of contributors.

I have tested this action in one of my test repos and it seems working fine. 
PR link: https://github.com/iamdharmesh/test-actions/pull/12

### Known Caveats/Issues
1. The contributor list only contains users who have an account on wp.org; other users are not included in the comment at the moment.
2. We are collecting contributors from the first 100 PR commits, first 100 comments, first 100 issues comments, first 100 reviews, etc. So, if a PR has more than 100 comments, then contributors who have commented after the first 100 comments will be skipped by this action.

### CODE REVIEW

**Comment by desrosj** [comment]
Thank you for taking a look @iamdharmesh! I'll take a look at this after the holiday break.

**Comment by desrosj** [comment]
I created desrosj/test-props-bot with the contents of this PR to test how this works. It looks like the [initial run works great](https://github.com/desrosj/wordpress-develop/pull/142#issuecomment-1874267988)! However additional changes are not being added to the comment, even though the action properly identifies the preexisting comment and says it's being updated.

**Comment by iamdharmesh** [comment]
> However additional changes are not being added to the comment, even though the action properly identifies the preexisting comment and says it's being updated.

@desrosj do you mean triggering the update of the contributors list when a new comment is created on a pull request? If yes, then we have to add the 'issue_comment' trigger in the yml file **[here](https://github.com/desrosj/wordpress-develop/pull/142/files#diff-f4f7a2fbcc805a4782ec1bc23de2902ede62d3bf67383b86cdeded136bd5a48fR3)**, as adding a comment on a PR falls under a separate trigger. Could you please try to add it and check if it works that way? However, one thing to note here is that the 'issue_comment' trigger runs against the default branch, so the in-progress action can't be seen directly under the PR in the checks list. You can check the action running under the 'Actions' tab of the repo.

The same applies to comments on pull_request reviews as well. We have to add the trigger `pull_request_review_comment`. I have tested this in my test repo, and you can find the workflow file [here](https://github.com/iamdharmesh/test-actions/blob/main/.github/workflows/wordpress-props.yml).

**Comment by desrosj** [comment]
Sorry, I wasn't super clear. The comment left by the action on the respective PR was not being updated based on new contributor activity on the PR. However, I did some more digging today and figured out what was going on.

The test accounts that I was using were not linked to a WordPress.org account, so they were being excluded from the list. When testing with other GH accounts that have an active wp.org connection, they were included.

While these should not be listed in the same way as the others with a `Co-authored-by` trailer, they should still be noted.

I started an attempt to solve this by adding a `unconnected` key to the `contributorTypes` that processes last and tacks onto the end of the comment, but for some reason the usernames are not properly mapping. I committed what I had so far to this PR with some other cleanup items (using official `core.*` methods instead of regular old `console.log()` ones, tabs for indentation, etc.), but I need to switch focus for the remainder of my day.

If you're ablet o take a look during yours, that would be great!

**Comment by iamdharmesh** [comment]
@desrosj I have fixed the `unconnected` username issue. The comment will list the unconnected contributors under the `# Unconnected` now.

**Comment by desrosj** [comment]
This looks really great! There are still some minor changes I'd like to see made, but I'm going to merge this and get it into an official repository under the WordPress org so I can spin up some issues for continued work.

**Review by desrosj — APPROVED** [review]

**Pull request merged**
